### PR TITLE
Adding Rails app to test folder / docker-compose to use activestorage gem as implementation to verify against

### PR DESCRIPTION
**Pull request by cheerfulstoic**
Also some other changes to start getting the tests working

I made this PR from my fork because that's where I started the work.  In the future I'll work in your repo.

Wanted to stop here briefly and verify the state of things before moving on.  I see that there isn't a schema for the `attachments`, but I can add that.  👍 ?  Also I would say we change the table names for the schemas:

`storage_blob` => `active_storage_blobs`
`storage_variant_records` => `active_storage_variant_records`

That way the tests can run against the same tables as what's being created in the Rails app.

Seem OK?  Any other thoughts / questions?

### CODE REVIEW

**Comment by michelson** [comment]
looks good to me 👍

**Comment by michelson** [comment]
indeed, there is no schema for attachment

**Review by michelson — APPROVED** [review]

**Comment by michelson** [comment]
I will merge this now and I will commit the latest changes on another PR

**Comment by cheerfulstoic** [comment]
👍  I'll pick this up again tomorrow night, thanks!

**Pull request merged**
